port: 3000

app:

log:
  level: DEBUG
  onConsole: true
  isJson: false
  trace: true
  maxSize: 2048

db:
  name: postgres
  host: localhost
  port: 5432
  user:
  password:
  idleConnection: 5
  openConnection: 10

grpc:
  host: localhost
  port: 3001
  size:
    send: 32
    receive: 32
